INSERT INTO SELL(SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES (SELL_SEQ.NEXTVAL,'삭제용',17,SYSDATE)
;

SELECT *
FROM SELL
ORDER BY SELL_NO DESC
;

    DELETE FROM SELL
    WHERE SELL_NO = 22
;
COMMIT;
ROLLBACK;
UPDATE SELL SET ITEM_NAME = '삭제용', COUNT = 3,  SELL_DT = sysdate
WHERE SELL_NO = 22
;

SELECT COUNT(*) AS CNT
FROM SELL
WHERE ITEM_NAME LIKE '%' || '��' ||'%'
AND COUNT LIKE '%' || 3 ||'%'
;

SELECT SELL_NO,ITEM_NAME,COUNT,TO_CHAR(SELL_DT, 'YY-MM-DD') AS DT
FROM (SELECT SELL_NO,ITEM_NAME,COUNT,SELL_DT,
            ROW_NUMBER()OVER (ORDER BY SELL_NO DESC) AS RNUM
        FROM SELL
        WHERE ITEM_NAME LIKE '%' || '��' || '%'
        AND COUNT LIKE '%' || 2 || '%'
        ) SE
WHERE SE.RNUM BETWEEN 1 AND 5
;

INSERT INTO SELL(SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES (21,'실험용',15,SYSDATE)
;

SELECT SELL_NO,ITEM_NAME,COUNT,SELL_DT
FROM SELL
WHERE SELL_NO = 21
;



SELECT COUNT(*) AS CNT
FROM SELL
WHERE 1 = 1 
AND ITEM_NAME LIKE '%' || '고구마' ||'%'
;
			
	       	  	--	AND COUNT LIKE '%' || #{searchTxt} ||'%'
