INSERT INTO B(B_NO,B_TITLE,B_WRITER,B_CON)
VALUES(B_SEQ.NEXTVAL, 'TEST' || B_SEQ.CURRVAL, 'TESTER', 'TEST중입니다.')
;

SELECT B_NO, B_TITLE, B_WRITER, TO_CHAR(B_DT, 'YYYY-MM-DD')AS B_DT
FROM B
ORDER BY B_NO DESC
;

COMMIT;
ROLLBACK;

