INSERT INTO M(M_NO,M_ID,M_PW,M_NM,M_BIRTH,M_JOINDT)
VALUES (M_SEQ.NEXTVAL,'TEST' || M_SEQ.CURRVAL, '1234','±è´©±¸',SYSDATE,SYSDATE)
;

SELECT *
FROM M
;

COMMIT;

SELECT B.B_NO, B.B_TITLE,B.B_WRITER,B.B_DT
FROM (SELECT B_NO, B_TITLE, B_WRITER, TO_CHAR(B_DT, 'YYYY-MM-DD')AS B_DT,
             ROW_NUMBER() OVER(ORDER BY B_NO DESC) AS RNUM
      FROM B
      WHERE 1 = 1
      --AND B_TITLE LIKE '%' ||  'E' || '%' 
     --AND B_WRITER LIKE '%' ||  'E' || '%'
    ) B
WHERE B.RNUM BETWEEN 1 AND 10
;

SELECT COUNT(*) AS CNT
FROM B
WHERE 1 = 1
;