INSERT INTO M(M_NO,M_ID,M_PW,M_NM,M_BIRTH,M_JOINDT)
VALUES (M_SEQ.NEXTVAL,'TEST' || M_SEQ.CURRVAL, '1234','±è´©±¸',SYSDATE,SYSDATE)
;

SELECT *
FROM M
;

COMMIT;


SELECT B_NO, B_TITLE, B_WRITER, TO_CHAR(B_DT, 'YYYY-MM-DD')AS B_DT
FROM B
WHERE 1 = 1
--AND B_TITLE LIKE '%' ||  'E' || '%' 
AND B_WRITER LIKE '%' ||  'E' || '%'
ORDER BY B_NO DESC

;