INSERT INTO BOARD(BNO, BTITLE, BCON, BWRITER)
VALUES(2, 'TEST2', 'TEST중입니다', '홍길동')
;
--기본값을 들어있으면 생략가능 BDT 생각해라
SELECT *
FROM BOARD
;

ROLLBACK;

COMMIT;


UPDATE  BOARD SET BWRITER = BWRITER|| 'NEW'
WHERE BNO = 2
;

SELECT * 
FROM BOARD
;

COMMIT;

DELETE FROM BOARD
WHERE BNO = 1
;

INSERT INTO HAMBUGER(PNO,PNAME,PRICE,STOCK,PDATE,ETC)
VALUES( 5, '쉑쉑', 2000, 5,'2021-04-01','비싸다') 
;

SELECT *
FROM HAMBUGER
;

COMMIT;
--등록일자별 /재고수량 합계를 구하시오
SELECT PDATE, SUM(STOCK)AS HAM
FROM HAMBUGER
GROUP BY PDATE
;

SELECT *
FROM PIZZA
--GROUP BY PDATE
;
INSERT INTO PIZZA(PNO,PNAME,PRICE,STOCK)
VALUES(5,'페퍼로니',30000,4)
;
--등록일자별 /재고수량 합계
SELECT PDATE,SUM(STOCK)AS SUM_STOCK
FROM PIZZA
GROUP BY PDATE
;
COMMIT;
ROLLBACK;


INSERT INTO PIZZA(PNO,PNAME,PRICE,STOCK)
VALUES(5,'페퍼로니',30000,4)
;

INSERT INTO VEGETABLE(SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES(2,'호박',5,'2019-11-21')
;

SELECT *
FROM SELL
;
COMMIT;
ROLLBACK;

--일자별 판매순위 1위인 상품을 구하는 쿼리,
--출력 일자, 상품, 판매량합계

--일자별 판매순위 1위
SELECT SELL_DT,ITEM_NAME,COUNT,
    RANK() OVER (PARTITION BY SELL_DT ORDER BY COUNT DESC) AS RNK
FROM SELL

;
--일자별 판매합계
SELECT SELL_DT, SUM(COUNT)
FROM SELL   
GROUP BY SELL_DT 
;

--최종출력,판매합계도 구해보자
SELECT E.SELL_DT,E.ITEM_NAME,E.COUNT
FROM 
        (SELECT SELL_DT,COUNT,ITEM_NAME,
            RANK() OVER (PARTITION BY SELL_DT ORDER BY COUNT DESC) AS RNK
        FROM SELL
        ORDER BY SELL_DT,ITEM_NAME) E 
WHERE RNK =1
order BY COUNT DESC
;

SELECT S.SELL_DT
FROM SELL S INNER JOIN ( SELECT  SUM(COUNT)
                        FROM SELL   
                        GROUP BY SELL_DT ) E
                        ON 1=1
;
--선생님 답
