SELECT *
FROM SELL2
;

INSERT INTO SELL2 (SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES (20,'고구마',17,to_date('19/11/30','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (19,'감자',3,to_date('19/11/30','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (18,'호박고구마',22,to_date('19/11/30','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (17,'호박',8,to_date('19/11/30','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (16,'감자',11,to_date('19/11/29','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (15,'호박',26,to_date('19/11/29','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (14,'고구마',4,to_date('19/11/29','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (13,'호박고구마',23,to_date('19/11/26','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (12,'애호박',7,to_date('19/11/26','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (11,'고구마',8,to_date('19/11/26','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (10,'감자',4,to_date('19/11/26','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (9,'호박',5,to_date('19/11/26','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (8,'고구마',10,to_date('19/11/23','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (7,'감자',8,to_date('19/11/23','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (6,'고구마',8,to_date('19/11/23','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (5,'감자',12,to_date('19/11/21','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (4,'호박고구마',3,to_date('19/11/21','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (3,'고구마',7,to_date('19/11/21','YY/MM/DD'))
;
INSERT INTO SELL2 (SELL_NO, ITEM_NAME,COUNT,SELL_DT)
VALUES (2,'호박',5,to_date('19/11/21','YY/MM/DD'))
;
COMMIT;

SELECT TO_CHAR(SELL_DT, 'YYYY-MM-DD') AS SELL_DT,
        ITEM_NAME, COUNT,
        RANK()OVER(PARTITION BY TO_CHAR(SELL_DT, 'YYYY-MM-DD') ORDER BY COUNT DESC) AS RNK
FROM SELL2
;


SELECT S.SELL_DT, S.ITEM_NAME, S.COUNT
FROM 
        (SELECT TO_CHAR(SELL_DT, 'YYYY-MM-DD') AS SELL_DT,
        ITEM_NAME, COUNT,
        RANK()OVER(PARTITION BY TO_CHAR(SELL_DT, 'YYYY-MM-DD') ORDER BY COUNT DESC) AS RNK
        FROM SELL2) S
WHERE S.RNK = 1