INSERT INTO SELL(SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES (SELL_SEQ.NEXTVAL,'고구마',17,'2019-11-30')
;

SELECT *
FROM SELL
ORDER BY SELL_NO DESC
;
COMMIT;

UPDATE SELL SET ITEM_NAME = '삭제', COUNT = 3
WHERE SELL_NO = 21
;

SELECT COUNT(*) AS CNT
FROM SELL
WHERE ITEM_NAME LIKE '%' || '고' ||'%'
AND COUNT LIKE '%' || 3 ||'%'
;

SELECT SELL_NO,ITEM_NAME,COUNT,TO_CHAR(SELL_DT, 'YY-MM-DD') AS DT
FROM (SELECT SELL_NO,ITEM_NAME,COUNT,SELL_DT,
            ROW_NUMBER()OVER (ORDER BY SELL_NO DESC) AS RNUM
        FROM SELL
        WHERE ITEM_NAME LIKE '%' || '고' || '%'
        AND COUNT LIKE '%' || 2 || '%'
        ) SE
WHERE SE.RNUM BETWEEN 1 AND 5
;

INSERT INTO SELL(SELL_NO,ITEM_NAME,COUNT,SELL_DT)
VALUES (SELL_SEQ.NEXTVAL,'고구마',15,SYSDATE)
;

SELECT SELL_NO,ITEM_NAME,COUNT,SELL_DT
FROM SELL
WHERE SELL_NO = 3
;