SELECT ENAME, SAL,JOB,
    ROW_NUMBER() OVER(ORDER BY SAL DESC) AS RNUM,
      RANK() OVER(ORDER BY SAL DESC) AS RNK,
       DENSE_RANK() OVER(ORDER BY SAL DESC) AS DRNK
FROM EMP
;

--ORACLE의 ROWNUM : 데이터 취득 순서대로 줄번호를 할당한다.
-- 조회된 인덱스 순서
SELECT ENAME, SAL, ROWNUM
FROM EMP
ORDER BY SAL DESC
;

SELECT ENAME, SAL, ROWNUM
FROM (SELECT ENAME,SAL
        FROM EMP
    ORDER BY SAL DESC)
;

--업무별 급여 순위를 구하시오.
SELECT  ENAME,SAL, DEPTNO,
   RANK() OVER(PARTITION BY JOB ORDER BY SAL DESC) AS RNK
FROM EMP
;

--부서별 급여순위 1위인 사원을 구하시오.
--실행순서를 생각하자
SELECT ENAME,SAL,DEPTNO
FROM(SELECT ENAME,SAL,DEPTNO,
   RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC)AS RNK
FROM EMP)
WHERE RNK = 1
;

--가장 많은 급여를 받는 사원의 / 부서명을 구하시오
-- HINT SUBQUERY -> WHERE
-- HINT SUBQUERY * 2
SELECT DEPTNO
FROM
    (SELECT ENAME,DEPTNO, SAL,
        RANK() OVER(ORDER BY SAL DESC) AS RNK
    FROM EMP)
WHERE RNK =1
;
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO 
        FROM  
        (SELECT ENAME,DEPTNO, SAL,
        RANK() OVER(ORDER BY SAL DESC) AS RNK
        FROM EMP)
    WHERE RNK =1) 
;





