
--창고(WAREHOUSE_NAME) 이름이 7글자을 넘고  보유중인 총수량이 1등인 창고를 아래 정답과 똑같이 출력하시오
SELECT W.WAREHOUSE_NAME,SUM(QUANTITY) AS QSUM,
      RANK() OVER(ORDER BY SUM(QUANTITY) DESC) AS RNK
FROM WAREHOUSES W INNER JOIN INVENTORIES I
                          ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
GROUP BY W.WAREHOUSE_NAME 
HAVING LENGTH(W.WAREHOUSE_NAME) > 7
;

SELECT LOWER(REPLACE(W2.WAREHOUSE_NAME,' ', '')) AS NAME, W2.QSUM
FROM (SELECT W.WAREHOUSE_NAME,SUM(QUANTITY) AS QSUM,
              RANK() OVER(ORDER BY SUM(QUANTITY) DESC) AS RNK
      FROM WAREHOUSES W INNER JOIN INVENTORIES I
                                  ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
      GROUP BY W.WAREHOUSE_NAME 
      HAVING LENGTH(W.WAREHOUSE_NAME) > 7) W2
WHERE W2.RNK = 1      
;

--창고(WAREHOUSE_NAME) 이름이 7글자을 넘고  보유중인 총수량이 1등인 창고를 아래 정답과 똑같이 출력하시오
SELECT REPLACE(W3.NAME,'f','F') AS NAME,W3.QSUM
FROM (SELECT LOWER(REPLACE(W2.WAREHOUSE_NAME,' ', '')) AS NAME, W2.QSUM
      FROM (SELECT W.WAREHOUSE_NAME,SUM(QUANTITY) AS QSUM,
                      RANK() OVER(ORDER BY SUM(QUANTITY) DESC) AS RNK
              FROM WAREHOUSES W INNER JOIN INVENTORIES I
                                          ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
              GROUP BY W.WAREHOUSE_NAME 
              HAVING LENGTH(W.WAREHOUSE_NAME) > 7) W2
     WHERE W2.RNK = 1   ) W3
;



SELECT SUM(QUANTITY) AS QSUM

FROM WAREHOUSES W INNER JOIN INVENTORIES I
                          ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
WHERE LENGTH(W.WAREHOUSE_NAME) > 7
;