INSERT INTO B(B_NO, B_TITLE,B_WRITER, B_CON)
VALUES(B_SEQ.NEXTVAL, 'TEST중', '홍길동', '테스트용')
;

SELECT *
FROM B
;

COMMIT;


INSERT INTO M(M_NO, M_ID,M_PW, M_NM, M_BIRTH, M_JOINDT)
VALUES(M_SEQ.NEXTVAL, 'TEST' || M_SEQ.CURRVAL, '1234', '홍길동', SYSDATE, SYSDATE)
;
SELECT *
FROM M
;
COMMIT;